# Generated by Django 5.0.7 on 2024-10-04 13:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0002_rename_historicalitem_historicalproduct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalShoppingList',
            new_name='HistoricalShopping',
        ),
        migrations.RenameModel(
            old_name='ShoppingList',
            new_name='Shopping',
        ),
        migrations.AlterModelOptions(
            name='historicalshopping',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Lista de compra', 'verbose_name_plural': 'historical Listas de compras'},
        ),
        migrations.AlterModelOptions(
            name='shopping',
            options={'verbose_name': 'Lista de compra', 'verbose_name_plural': 'Listas de compras'},
        ),
    ]
