# Generated by Django 5.0.7 on 2024-10-04 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0003_rename_historicalshoppinglist_historicalshopping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shopping_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shopping_list.shopping'),
        ),
    ]
