# Generated by Django 5.1 on 2024-10-14 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0004_alter_product_shopping_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_shoppings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_shoppings', to=settings.AUTH_USER_MODEL),
        ),
    ]
