# Generated by Django 5.1 on 2024-10-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0005_shopping_shared_with_alter_shopping_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping',
            name='shared_with',
        ),
    ]
