# Generated by Django 5.1 on 2024-10-17 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0006_remove_shopping_shared_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shopping_list',
        ),
        migrations.DeleteModel(
            name='HistoricalProduct',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
