# Generated by Django 5.1 on 2024-10-17 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_shopping_list'),
        ('shopping_list', '0007_remove_product_shopping_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shopping_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shopping_list.shopping'),
        ),
    ]
